### ISSUE TITLE
PDFIX DLL works on one IIS Server but does not work on other.

### ISSUE THREAD

**Issue by mpriyam81** [pdfix/PDFixSDKSample-csharp#4]
I have used pdfix dll for converting pdf to html to render in a div on my website. It works on Localhost. It works on Test Server. But it does not work on my AWS Production server.

Throws error: "System.Exception: Unable to load library pdfix, error 126     at PDFixSDK.NativeMethods.LoadLibrary(String dllToLoad)     at PDFixSDK.Pdfix.Pdfix..ctor()     at PDFix.App.Module.ConvertToHtml.Run(String openPath, String savePath, String configPath, PdfHtmlParams htmlParams) "

**Comment by jozefbaranec** [comment]
Please check if you have installed the latest [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) on the production server.

**Comment by mpriyam81** [comment]
Installed as advised. And yes it works well now. Thanks. Excellent and quick.
